version: "0.0"
services:
   webapp:
      build: .
      ports:
         - "4010:4010"
      environment:
         DOCKER_COMPOSE_TEST_ENV: production
         MAX: hello
      volumes:
         - ./:/usr/src/app
